// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {api} from '../models';
import {db} from '../models';
import {config} from '../models';
import {storage} from '../models';
import {main} from '../models';
import {core} from '../models';
import {ipfs} from '../models';

export function AddWallet(arg1:string,arg2:string):Promise<void>;

export function BrowseForFolder():Promise<string>;

export function CancelMigration():Promise<void>;

export function ClearFailed():Promise<number>;

export function DeleteAsset(arg1:number):Promise<void>;

export function DeleteWallet(arg1:string,arg2:boolean):Promise<void>;

export function DeleteWalletWithUnpin(arg1:string):Promise<void>;

export function DiscoverServers():Promise<Array<api.DiscoveredServer>>;

export function GetAssetGatewayURL(arg1:number):Promise<Record<string, string>>;

export function GetAssetStats():Promise<Record<string, number>>;

export function GetAssets(arg1:number,arg2:number,arg3:string):Promise<Array<db.Asset>>;

export function GetConfig():Promise<config.Config>;

export function GetFailedAssets():Promise<Array<db.Asset>>;

export function GetIPFSRepoPath():Promise<string>;

export function GetMigrationStatus():Promise<storage.MigrationStatus>;

export function GetNFTsWithAssets(arg1:number,arg2:number):Promise<Array<db.NFT>>;

export function GetRecentActivity(arg1:number):Promise<Array<db.Asset>>;

export function GetStatus():Promise<Record<string, any>>;

export function GetStorageInfo():Promise<main.StorageInfo>;

export function GetStorageLocation():Promise<storage.StorageLocation>;

export function GetStorageType(arg1:string):Promise<string>;

export function GetSyncProgress():Promise<core.ServiceStatus>;

export function GetVersion():Promise<string>;

export function GetWallets():Promise<Array<db.Wallet>>;

export function IsBackupPaused():Promise<boolean>;

export function ListStorageLocations():Promise<Array<storage.StorageLocation>>;

export function MigrateStorage(arg1:string):Promise<void>;

export function PauseBackup():Promise<void>;

export function PreviewAsset(arg1:number,arg2:number):Promise<Record<string, any>>;

export function RepinAsset(arg1:number):Promise<void>;

export function RepinZeroSizeAssets():Promise<number>;

export function ResetDatabase():Promise<void>;

export function ResumeBackup():Promise<void>;

export function ResyncAsset(arg1:number):Promise<void>;

export function RetryAllFailed():Promise<number>;

export function RetryAsset(arg1:number):Promise<void>;

export function ShowInFinder():Promise<void>;

export function SyncWallet(arg1:string):Promise<void>;

export function UnpinAsset(arg1:number):Promise<void>;

export function UpdateSettings(arg1:Record<string, any>):Promise<void>;

export function UpdateWalletAlias(arg1:string,arg2:string):Promise<void>;

export function UpdateWalletSettings(arg1:string,arg2:boolean,arg3:boolean):Promise<void>;

export function ValidateStoragePath(arg1:string):Promise<void>;

export function VerifyAndFixPins():Promise<Record<string, number>>;

export function VerifyAsset(arg1:number):Promise<ipfs.VerifyResult>;
