// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddWallet(arg1, arg2) {
  return window['go']['main']['App']['AddWallet'](arg1, arg2);
}

export function BrowseForFolder() {
  return window['go']['main']['App']['BrowseForFolder']();
}

export function CancelMigration() {
  return window['go']['main']['App']['CancelMigration']();
}

export function ClearFailed() {
  return window['go']['main']['App']['ClearFailed']();
}

export function DeleteAsset(arg1) {
  return window['go']['main']['App']['DeleteAsset'](arg1);
}

export function GetAssetGatewayURL(arg1) {
  return window['go']['main']['App']['GetAssetGatewayURL'](arg1);
}

export function GetAssetStats() {
  return window['go']['main']['App']['GetAssetStats']();
}

export function GetAssets(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetAssets'](arg1, arg2, arg3);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetFailedAssets() {
  return window['go']['main']['App']['GetFailedAssets']();
}

export function GetIPFSRepoPath() {
  return window['go']['main']['App']['GetIPFSRepoPath']();
}

export function GetMigrationStatus() {
  return window['go']['main']['App']['GetMigrationStatus']();
}

export function GetNFTsWithAssets(arg1, arg2) {
  return window['go']['main']['App']['GetNFTsWithAssets'](arg1, arg2);
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function GetStorageInfo() {
  return window['go']['main']['App']['GetStorageInfo']();
}

export function GetStorageLocation() {
  return window['go']['main']['App']['GetStorageLocation']();
}

export function GetStorageType(arg1) {
  return window['go']['main']['App']['GetStorageType'](arg1);
}

export function GetSyncProgress() {
  return window['go']['main']['App']['GetSyncProgress']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function GetWallets() {
  return window['go']['main']['App']['GetWallets']();
}

export function IsBackupPaused() {
  return window['go']['main']['App']['IsBackupPaused']();
}

export function ListStorageLocations() {
  return window['go']['main']['App']['ListStorageLocations']();
}

export function MigrateStorage(arg1) {
  return window['go']['main']['App']['MigrateStorage'](arg1);
}

export function PauseBackup() {
  return window['go']['main']['App']['PauseBackup']();
}

export function PreviewAsset(arg1, arg2) {
  return window['go']['main']['App']['PreviewAsset'](arg1, arg2);
}

export function RepinAsset(arg1) {
  return window['go']['main']['App']['RepinAsset'](arg1);
}

export function RepinZeroSizeAssets() {
  return window['go']['main']['App']['RepinZeroSizeAssets']();
}

export function ResetDatabase() {
  return window['go']['main']['App']['ResetDatabase']();
}

export function ResumeBackup() {
  return window['go']['main']['App']['ResumeBackup']();
}

export function ResyncAsset(arg1) {
  return window['go']['main']['App']['ResyncAsset'](arg1);
}

export function RetryAllFailed() {
  return window['go']['main']['App']['RetryAllFailed']();
}

export function RetryAsset(arg1) {
  return window['go']['main']['App']['RetryAsset'](arg1);
}

export function ShowInFinder() {
  return window['go']['main']['App']['ShowInFinder']();
}

export function SyncWallet(arg1) {
  return window['go']['main']['App']['SyncWallet'](arg1);
}

export function UnpinAsset(arg1) {
  return window['go']['main']['App']['UnpinAsset'](arg1);
}

export function UpdateSettings(arg1) {
  return window['go']['main']['App']['UpdateSettings'](arg1);
}

export function UpdateWalletSettings(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateWalletSettings'](arg1, arg2, arg3);
}

export function ValidateStoragePath(arg1) {
  return window['go']['main']['App']['ValidateStoragePath'](arg1);
}

export function VerifyAndFixPins() {
  return window['go']['main']['App']['VerifyAndFixPins']();
}

export function VerifyAsset(arg1) {
  return window['go']['main']['App']['VerifyAsset'](arg1);
}
